SELECT
    P.PRODUCT_CODE,
    SUM(O.SALES_AMOUNT) * P.PRICE SALES
FROM
    PRODUCT P
JOIN 
    OFFLINE_SALE O 
        ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SALES DESC,
    P.PRODUCT_CODE ASC