-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
WHERE MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
# HAVING SALES_DATE, MONTH(SALES_DATE) = 1
ORDER BY B.CATEGORY ASC
;