WITH MAX_TABLE AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) YEAR,
        MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM
        ECOLI_DATA 
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(E.DIFFERENTIATION_DATE) YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E
    JOIN
        MAX_TABLE M
    ON
        YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC