SELECT 
    B.CATEGORY, 
    SUM(S.SALES) TOTAL_SALES
FROM 
    BOOK_SALES S 
        JOIN BOOK B
ON 
    S.BOOK_ID = B.BOOK_ID
WHERE 
    MONTH(S.SALES_DATE) = 1
GROUP BY 
    B.CATEGORY
ORDER BY 
    B.CATEGORY